---
title: "Images for reports"
author: "Jens von Bergmann"
date: "Last updated at `r format(Sys.time(), '%d %B, %Y - %H:%M',tz='America/Vancouver')`"
output: rmarkdown::github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	fig.retina = 2,
	dpi = 150,
	fig.width = 7,
	fig.height = 5
)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(CanCovidData)
library(lubridate)
library(ggtext)
#library(segmented)
library(broom)
source(here::here("R/helpers.R"))


major_restrictions <- c("2020-03-18"="Phase 1","2020-11-07"="No private\ngatherings","2020-11-19"="Masks in stores\nTravel discouraged","2021-03-29"="No indoor dining\nNo indoor group activity\nMasks grades 4-12",
                        "2021-08-25"="Indoor Masks")
major_restriction_labels <- c("2020-03-18"="Phase 1","2020-11-07"="No private\ngatherings","2020-11-19"="Masks in stores\nTravel discouraged","2021-03-07"="No indoor dining\nNo indoor group activity\nMasks grades 4-12",
                              "2021-08-25"="Indoor Masks")
major_restrictions_y <- c("2020-03-18"=1,"2020-11-07"=0.1,"2020-11-19"=0.3,"2020-03-29"=0.1,"2021-08-25"=1)
minor_restrictions <- c("2020-03-11","2020-03-12","2020-03-16","2020-03-17",
                        "2020-03-21","2020-03-22","2020-03-26","2020-04-18",
                        "2020-06-18","2020-08-21","2020-09-08","2020-10-26","2021-04-30",
                        "2021-07-28","2021-08-06")
major_reopenings <- c("2020-05-19"="Phase 2","2020-06-24"="Phase 3",
                      "2021-05-25"="Step 1\nreopening","2021-06-15"="Step 2\nreopening",
                      "2021-07-01"="Step 3\nreopening")
major_reopenings_y_fact <- c(1,1,1,0.8,0.6)
minor_reopenings <- c("2020-05-14","2020-06-01","2020-06-08",
                      "2020-06-30","2020-07-02","2020-09-10","2020-12-15")

restriction_markers <- function(major_size=1,minor_size=0.25){
  list(
    geom_vline(xintercept = as.Date(minor_reopenings),
               linetype="dashed",color="darkgreen",size=minor_size),
    geom_vline(xintercept = as.Date(names(major_reopenings)),linetype="dashed",color="darkgreen",size=major_size),
    geom_vline(xintercept = as.Date(names(major_restrictions)),linetype="dashed",color="brown",size=major_size),
    geom_vline(xintercept = as.Date(minor_restrictions),
               linetype="dashed",color="brown",size=minor_size)
)}

full_labels <- function(label_y,
                        major_restriction_labels = c("2020-03-18"="Phase 1","2020-11-07"="No private\ngatherings"),
                        major_restrictions_y = c(1,0.15)){
  c(restriction_markers(),list(
    geom_label(data = tibble(Date=as.Date(names(major_reopenings)),
                             count=label_y*major_reopenings_y_fact,
                             label=as.character(major_reopenings)),
               aes(label=label),size=4,alpha=0.7,color="darkgreen"),
    geom_label(data = tibble(Date=as.Date(names(major_restriction_labels)),
                             label=as.character(major_restriction_labels),
                             count=as.numeric(major_restrictions_y)),
               aes(label=label),size=4,alpha=0.7,color="brown")
  ))
}


ha_colours <- setNames(c(sanzo::trios$c157,sanzo::trios$c149),
                       c("Fraser","Rest of BC","Vancouver Coastal" , "Vancouver Island", "Interior", "Northern"))

share_to_ratio <- function(s)1/(1/s-1)
ratio_to_share <- function(r)1/(1+1/r)
get_n501y_data <- function(live=FALSE){
  if (live)
  read_csv("http://www.bccdc.ca/Health-Info-Site/Documents/VoC/Figure1_weeklyreport_data.csv") %>%
    rename(epiweek=Epiweek,epi_cdate=`Epiweek - Start Date`,patient_ha=Region,
           prop_voc=`Proportion of VoC`)
  else
  read_csv(here::here("data/COVID19_VoC_data.csv"),col_types = cols(.default="c")) %>%
    mutate(across(c("epiweek",prop_voc),as.numeric),epi_cdate=as.Date(epi_cdate)) %>%
  bind_rows(tibble(patient_ha=c("British Columbia", "Fraser", "Interior", "Northern", 
                                "Vancouver Coastal", "Island"),
                   epiweek=18,
                   epi_cdate=as.Date("2021-05-02"),
                   prop_voc=c(83,82,83,45,92,82))) %>%
                   #prop_voc=c(85,86,83,45,93,84))) %>%
  bind_rows(tibble(patient_ha=c("British Columbia", "Fraser", "Interior", "Northern", 
                                "Vancouver Coastal", "Island"),
                   epiweek=19,
                   epi_cdate=as.Date("2021-05-09"),
                   prop_voc=c(85,82,89,63,94,77))) 
                   #prop_voc=c(89,88,89,63,94,78))) 
}

```

```{r}

bc_voc_data <- get_n501y_data() %>%
  mutate(prop_voc=as.numeric(prop_voc)) %>%
  mutate(Date=as.Date(epi_cdate)+4,
         share_voc=prop_voc/100) %>%
  #left_join(get_b.1.617(),by=c("patient_ha","epiweek")) %>%
  #mutate(share_voc=share_voc+coalesce(prop_b.1.617,0)/100) %>%
  mutate(ratio_voc=share_to_ratio(share_voc)) %>%
  mutate(Day=difftime(Date,min(Date),units = "day") %>% unclass) 

n501y <- bc_voc_data %>%
  filter(patient_ha=="British Columbia") %>%
  select(Date,Week=epiweek,share_voc,ratio_voc,Day) 

# break_day <- n501y %>% filter(Date>=as.Date("2021-04-01")) %>% 
#                                 head(1) %>% 
#                                 pull(Day)
break_day <- #as.Date(c("2021-04-01","2021-05-20")) %>% 
  as.Date(c("2021-04-01")) %>% 
  difftime(min(n501y$Date),units = "day") %>% 
  as.integer

model.n501y <- lm(log(ratio_voc)~Day,data=n501y%>% filter(as.integer(Week)>=7),Week<22)
model.n501y.s <- segmented::segmented(model.n501y,psi = break_day)
prediction.n501y <- tibble(Date=seq(as.Date("2021-02-01"),Sys.Date(),by="day")) %>%
  mutate(Day=difftime(Date,min(n501y$Date),units = "day") %>% unclass) %>%
  mutate(share_voc = predict(model.n501y.s,newdata = .) %>% exp %>% ratio_to_share) 

```

```{r}
all_data <- get_british_columbia_case_data() %>%
  count(Date=`Reported Date`,name="Cases") %>%
  filter(Date>=as.Date("2020-03-01")) %>%
  mutate(stl=add_stl_trend_m(Cases)) %>%
  mutate(Trend=stl$trend,
         Random=stl$remainder,
         Seasonal=stl$seasonal) %>%
  select(-stl) %>%
  mutate(Cleaned=Cases/Seasonal) %>%
  left_join(prediction.n501y, by="Date") %>%
  mutate(`Wild type`=Trend*(1-share_voc)) %>% 
  mutate(`Wild type`=coalesce(`Wild type`,Trend)) %>%
  mutate(Combined=Trend) %>%
  mutate(Trend=`Wild type`)

# stl_fan <- all_data %>%
#   get_stl_fan(stl_floor = 0)


start_date <- as.Date("2020-04-25")
end_predict_date<- as.Date("2021-06-01")
projection_days <- 14

model_data <- all_data %>% 
  filter(Date>=start_date) %>%
  filter(Date<=end_predict_date) %>%
  mutate(day=difftime(Date,start_date,units="day") %>% as.integer) %>%
  mutate(log_Trend=log(Trend)) 

model.lm <- lm(log_Trend ~ day,data=model_data)
  

model.s <- segmented::segmented(model.lm,npsi=6)

change_points <- model.s$psi %>% 
  as_tibble() %>% 
  mutate(Date=start_date+Est.)

if (FALSE){
  added_change_points <- as.Date(c("2020-05-09")) %>% 
    #as.Date(c("2020-05-09")) %>% 
    difftime(start_date) %>% 
    as.integer
  model.s <- segmented::segmented(model.lm,psi=c(change_points$Est.,added_change_points) %>% sort)
  
  change_points <- model.s$psi %>% 
    as_tibble() %>% 
    mutate(Date=start_date+Est.)
}
# initial_phase <- tidy(model.s) %>% 
#   slice(1,2) %>%
#   pull(estimate)


predict_data <- list(seq(as.Date("2020-03-20"),start_date,by="day"),
                     seq(max(all_data$Date),max(all_data$Date)+projection_days,by="day")) %>%
  lapply(function(dates){
    tibble(Date=dates) %>%
      mutate(day=difftime(Date,start_date,units = "day") %>% as.integer) %>%
      mutate(log_count=predict(model.s,newdata=.)) %>%
      mutate(count=exp(log_count))
  }) 

growth_rates <- tidy(model.s) %>%
  filter(term!="(Intercept)",!grepl("psi",term)) %>%
  mutate(r=cumsum(estimate)) %>%
  mutate(R=exp(r*6.5)) 

cutoff_data <- tibble(min=c(start_date,sort(change_points$Date)) %>% as.character()) %>%
  mutate(max=lead(min) %>% coalesce(.,end_predict_date %>% as.character()),
         predict_max=lead(min) %>% coalesce(.,as.character(end_predict_date+projection_days))) %>%
  mutate_all(as.Date) %>%
  mutate(t=as.character(row_number() %% 2)) %>%
  mutate(mid=min+as.numeric(difftime(max,min,units="day"))/2) %>%
  bind_cols(growth_rates %>% select(r,R)) %>%
  mutate(label=paste0("Wild type\nr=",scales::percent(r,accuracy = 0.1),"\nR=",round(R,2))) %>%
  mutate(mid=case_when(mid==min(mid) ~ mid-12,TRUE ~ mid)) #%>%
  #filter(min<max(change_points$Date)-1) # drop last one
  
```


```{r bc-overview, fig.height=6, fig.width=8}
label_y <- max(model_data$Cases) * 0.85

g <- all_data %>%
  left_join(model_data %>% 
              mutate(Fitted=predict(model.s,new_data=.) %>% exp()) %>%
              select(Date,Fitted),by="Date")%>%
  #filter(Date<=min(filter(stl_fan,max-min>0.8)$Date)) %>%
  #filter(Date<=stl_fan$Date) %>%
  pivot_longer(c("Cases","Wild type","Cleaned","Combined","Fitted"),names_to="type",values_to="count") %>%
  filter(type!="Wild type" | Date>=as.Date("2021-02-01")) %>%
  mutate(type=factor(type,levels=c("Cases","Cleaned","Wild type","Fitted","Combined"))) %>%
  filter(Date<=end_predict_date|type!="Wild type") %>%
  #filter(Date>=as.Date("2020-11-01")) %>%
  ggplot(aes(x = Date, y = count,color=type,size=type)) + 
  geom_rect(data=cutoff_data,# %>% filter(max<as.Date("2021-03-01")),
            aes(xmin=min,xmax=max,fill=t), inherit.aes = FALSE,
            ymin=0,ymax=Inf,show.legend = FALSE,alpha=0.5) +
  scale_fill_manual(values=c("#dddddd","#aaaaaa")) +
  #geom_ribbon(data=stl_tail,aes(x=Date,ymin=min,ymax=max),fill="black",colour="black",size=1,inherit.aes=FALSE) +
  full_labels(label_y,major_restriction_labels=major_restriction_labels,
              major_restrictions_y=major_restrictions_y*label_y) +
  geom_point(data=~filter(.,type=="Cases"),shape=21) +
  geom_line(data=~filter(.,type!="Cases")) +
  scale_size_manual(values=c("Cases"=0.5,"Cleaned"=0.25,
                              "Wild type"=1,
                              "Combined"=1,"Fitted"=0.75),
                    guide="none") +
  #geom_line(data=stl_fan,aes(x=Date,y=value,colour="Combined",group=run),size=1) +
  #geom_vline(data=change_points %>% bind_rows(tibble(Date=start_date)),aes(xintercept = Date)) +
  theme_bw() +
  theme(legend.position = "bottom") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank()) +
  scale_x_date(breaks="month",labels=function(d)strftime(d,"%b")) +
  scale_color_manual(values=c("Cases"="grey","Cleaned"="darkgrey",
                              "Wild type"="grey40",
                              "Combined"="black","Fitted"="steelblue"),
                     labels=c("Cases"="Raw cases","Cleaned"="Cases adjusted for weekly pattern",
                              "Wild type"="Wild type",
                              "Combined"="Wild type and VOC","Fitted"="Fitted wild type")) +
  #geom_line(data=predict_data[[1]],color="steelblue",size=1,linetype="dotted") +
  #geom_line(data=predict_data[[2]],color="steelblue",size=1,linetype="dotted") +
  guides(color = guide_legend(override.aes = list(linetype = c("Cases"=NA, "Cleaned"=1,
                                                               "Wild type"=1,"Fitted"=1, "Combined"=1),
                                                  shape = c("Cases"=21,"Cleaned"=NA,
                                                            "Wild type"=NA,"Fitted"=NA, "Combined"=NA)) ) ) +
  geom_label(data=cutoff_data,# %>% filter(max<as.Date("2021-03-01")),
             y=max(model_data$Cases*0.98),
                            aes(label=label,x=mid),inherit.aes = FALSE,size=3,alpha=0.8) +
  labs(title=paste0("Covid-19 daily new cases in British Columbia (up to ",strftime(max(all_data$Date),"%a %b %d"),")"),
       subtitle="Timeline of <b style='color:#A52A2A;'>closure</b> and <b style='color:#006400;'>reopening</b> events",
       x=NULL,y="Number of daily cases",color=NULL,caption="MountainMath, Data: BCCDC") +
  theme(plot.subtitle = element_markdown()) +
  expand_limits(x=as.Date("2021-09-08"))
g 
```


```{r bc-hospitalizations}
d<-get_can_covid_tracker_data("bc") %>%
  mutate(Date=as.Date(date))

dd<-get_british_columbia_case_data() %>%
  count(Date=`Reported Date`,name="Cases")

d %>%
  pivot_longer(c("total_hospitalizations","total_criticals","change_cases")) %>%
  select(Date,name,value) %>%
  mutate(value=as.integer(value)) %>%
  bind_rows(dd %>% rename(value=Cases) %>% mutate(name="Cases")) %>%
  filter(Date>=as.Date("2020-08-01")) %>%
  mutate(value=pmax(1,value)) %>%
  group_by(name) %>%
  arrange(desc(Date)) %>%
  filter(cumsum(value)>0) %>%
  mutate(stl=add_stl_trend_m(value)) %>%
  mutate(trend=stl$trend) %>%
  filter(name!="change_cases") %>%
  filter(Date>=as.Date("2020-09-01")) %>%
  mutate(name=recode(name,"total_criticals"="ICU census","total_hospitalizations"="Hospital census")) %>%
ggplot(aes(x=Date,y=trend,colour=name)) +
  geom_point(aes(y=value),size=0.5,shape=21) +
  geom_line() +
  scale_y_continuous(trans="log",breaks=2^seq(0,10)) +
  scale_x_date(date_labels = "%b %Y",breaks = "month") +
  theme_bw() +
  scale_colour_manual(values=c("ICU census"="#ff80ff","Hospital census"="#008080",Cases="#008000")) +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=60,hjust=1)) +
  labs(title="British Columbia COVID-19 cases, hospital and ICU census",
       x=NULL,y=NULL,colour=NULL,
       caption="Data: BCCDC for cases, Canada Covid-19 tracker for hospital and ICU census")
```

```{r icu-share}
d %>%
  #pivot_longer(c("total_hospitalizations","total_criticals","change_cases")) %>%
  mutate_at(c("total_criticals","total_hospitalizations","change_cases"),as.integer) %>%
  mutate(`ICU share`=total_criticals/total_hospitalizations,
         `Hospitalization rate`=total_hospitalizations/lag(change_cases,n=14,order_by = Date)) %>%
  pivot_longer(c("ICU share","Hospitalization rate")) %>%
  select(Date,name,value) %>%
  #mutate(value=as.integer(value)) %>%
  #bind_rows(dd %>% rename(value=Cases) %>% mutate(name="Cases")) %>%
  filter(Date>=as.Date("2020-08-01")) %>%
  #mutate(value=pmax(1,value)) %>%
  group_by(name) %>%
  arrange(desc(Date)) %>%
  filter(cumsum(value)>0) %>%
  #mutate(stl=add_stl_trend(value)) %>%
  #mutate(trend=stl$trend) %>%
  filter(name!="change_cases") %>%
  filter(Date>=as.Date("2020-09-01")) %>%
  filter(grepl("ICU",name)) %>%
  #mutate(name=recode(name,"total_criticals"="ICU census","total_hospitalizations"="Hospital census")) %>%
ggplot(aes(x=Date,y=value,colour=name)) +
  geom_point(aes(y=value),size=0.5,shape=21) +
  geom_smooth(span=0.3,se=FALSE) +
  scale_y_continuous(labels=scales::percent) +
  expand_limits(y=0) +
  #scale_y_continuous(trans="log",breaks=2^seq(0,10)) +
  scale_x_date(date_labels = "%b %Y",breaks = "month") +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=60,hjust=1)) +
  labs(title="British Columbia share of COVID-19 hospitalizations in ICU",
       x=NULL,y=NULL,colour=NULL,
       caption="Data: Canada Covid-19 tracker")
```


```{r hospital-admissions}
admissions <- read_csv("https://mountainmath.ca/bc_total_hospitalizations.csv") 
plot_data<-admissions %>%
  #bind_rows(new_data) %>%
  group_by(HA) %>%
  mutate(change=total_hospitalized-lag(total_hospitalized,order_by = ScrapeDate)) %>%
  filter(!is.na(change))



plot_data %>% 
  filter(ScrapeDate %in% ((.) %>%filter(HA=="BC",change>0) %>% pull(ScrapeDate))) %>%
  mutate(lastDate=lag(ScrapeDate,order_by = ScrapeDate)) %>%
  mutate(diff=difftime(ScrapeDate,lastDate,units = "day") %>% as.integer) %>%
  mutate(Date=ScrapeDate,
         estimate=change/diff) %>%
  group_by(HA) %>%
  complete(Date=seq(min(ScrapeDate),max(ScrapeDate),by="day")) %>%
  arrange(Date) %>%
  fill(estimate,.direction = "up") %>%
  select(HA,Date,change,estimate) %>%
  ungroup %>%
ggplot(aes(x=Date,y=estimate,fill=HA)) +
  #scale_y_continuous(trans="log") +
  geom_bar(stat="identity") +
  geom_smooth(se=FALSE,span=0.3,colour="black") +
  scale_fill_discrete(guide="none")  +
  facet_wrap("HA",scales="free_y") +
  labs(y="Hospital admissions") +
  labs(title="Hospital admissions",
       caption="Scraped from BCCDC Dashboard",x=NULL,y="Number of daily hospitalizations")
```




```{r hr-trend-recent}
pop_data <- read_csv(here::here("data/hr_pop.csv")) %>%
  select(HR_UID=Region,HR=`Health Service Delivery Area`,Population=Total)

data <- get_british_columbia_hr_case_data() %>%
  rename(HA=`Health Authority`,HR=`Health Region`) %>%
  filter(!(HA %in% c("Out of Canada","All")),!(HR %in% c("All","Unknown"))) %>%
  filter(Date>=as.Date("2020-03-01")) %>%
  group_by(HR,HA) %>%
  mutate(Trend=extract_stl_trend_m(Cases+1)-1,
         Seasonal=extract_stl_seasonal_m(Cases+1)) %>%
  mutate(Cleaned=Cases/Seasonal-1) %>%
  left_join(read_csv(here::here("data/ha_pop.csv")) %>%
              select(HA=`Health Authority`,HA_Population=Total), by="HA") %>%
  left_join(pop_data, by="HR") %>%
  mutate(Population=coalesce(Population,HA_Population)) %>%
  ungroup() %>%
  mutate(Cases_0=Cases,Trend_0=Trend,Cleand_0=Cleaned) %>%
  mutate_at(c("Cases","Cleaned","Trend"),function(d)d/.$Population*100000)


# stl_fan <- data %>%
#   filter(!(HR %in% c("All","Unknown"))) %>%
#   group_by(HA,HR) %>%
#   get_stl_fan()



label_y <- max(data$Cases) * 0.9 

g <- data %>% 
  filter(!(HR %in% c("All","Unknown")),Date>=as.Date("2021-07-01")) %>%
  pivot_longer(c("Cases","Trend","Cleaned"),names_to="type",values_to="count") %>%
  filter(count>0) %>%
  #left_join(stl_fan %>% group_by(HA,HR) %>% summarize(max_date=min(Date),.groups="drop"), by=c("HA","HR")) %>%
  #filter(Date<=max_date) %>%
  ggplot(aes(x = Date, y = count)) + 
  #geom_point(data=~filter(.,type=="Cases"),size=0.5,alpha=0.1,aes(color=HA,group=HR)) +
  #geom_line(data=~filter(.,type=="Cleaned"),size=0.5,alpha=0.1,aes(color=HA,group=HR)) +
  # geom_ribbon(data=stl_tail,aes(x=Date,ymin=min,ymax=max,fill=HA,color=HA,group=HR),size=0.75,
  #             inherit.aes=FALSE,show.legend = 'none') +
  geom_line(data=~filter(.,type=="Trend"),aes(color=HA,group=HR),size=0.75) +
  #geom_line(data=stl_fan,aes(x=Date,y=value,color=HA,group=interaction(HR,run)),size=0.75) +
  theme_bw() +
  scale_x_date(breaks="month",labels=function(d)strftime(d,"%b")) +
  theme(legend.position = "bottom") +
  scale_color_manual(values=ha_colours[intersect(names(ha_colours),unique(data$HA))]) +
  scale_fill_manual(values=ha_colours[intersect(names(ha_colours),unique(data$HA))]) +
  ggrepel::geom_text_repel(data = ~filter(.,Date==max(Date),type=="Trend",count>=2),
                           aes(label=HR),show.legend=FALSE,
                           nudge_x = 7,direction="y",size=3,hjust=0,
                           segment.color="black",segment.size = 0.25,colour="black") +
  labs(title=paste0("Covid-19 daily new cases trend lines in British Columbia (up to ",strftime(max(data$Date),"%a %b %d"),")"),
       subtitle="Timeline of <b style='color:#A52A2A;'>closure</b> and <b style='color:#006400;'>reopening</b> events",
       x=NULL,y="Daily cases per 100k population",color=NULL,caption="MountainMath, Data: BCCDC, BC Stats") +
  theme(plot.subtitle = element_markdown()) +
  restriction_markers(0.5,0.25) +
  expand_limits(x=max(data$Date)+40)

g + scale_y_continuous(trans="log", breaks=2^seq(-5,10)) +
  labs(y="Daily cases per 100k population (log scale)") +
  facet_wrap("HA") +
  coord_cartesian(ylim=c(0.1,NA))

```

```{r wastewater-covid}
plants <- c("Annacis Island","Iona Island","Lions Gate","Lulu Island","Northwest Langley")

phac_wastewater <- read_csv("https://health-infobase.canada.ca/src/data/covidLive/wastewater/covid19-wastewater.csv") |>
  filter(region=="Vancouver") |>
  mutate(Plant=gsub("Vancouver ","",Location),measure="PHAC") |>
  select(Date,Plant,measure,value=viral_load) 

wastewater_data <- plants %>% 
  lapply(get_data_for_plant) %>%
  bind_rows() %>%
  complete(Date=as.Date(c("2021-12-25","2020-12-25")),Plant,Version) %>%
  rename(Concentration=Value,`Flow adjusted`=DailyLoad) |>
  pivot_longer(c("Concentration","Flow adjusted"),names_to="measure",values_to = "value") |>
  select(Date,Plant,measure,value) |>
  bind_rows(phac_wastewater) #|>
  #filter(!is.na(value))



bc_cases <- CanCovidData::get_british_columbia_hr_case_data() %>%
  select(Date, HA=`Health Authority`,HR=`Health Region`,Cases) %>%
  filter(Date>=min(wastewater_data$Date)-7)


joint_data_for <- function(HRs, WPs,label=NULL){
  if (length(WPs)==1 & is.null(names(WPs))) WPs=setNames(1,WPs)
  if (is.null(label)) label = paste0(paste0(names(WPs),collapse = " & ")," / ",
                                     paste0(HRs,collapse = " & "))
  wd<-wastewater_data %>%
    filter(Plant %in% names(WPs)) %>%
    mutate(weight=WPs[Plant]) %>%
    group_by(Date,measure) %>%
    mutate(weight=weight/sum(weight)) %>%
    #filter(!(Plant%in% c("Northwest Langley","Annacis Island") & weight==1)) %>%
    summarise(value=sum(value*weight), .groups="drop")
  cs <- bc_cases %>% 
    filter(HR %in% HRs) %>%
    group_by(Date) %>%
    summarize(Cases=sum(Cases),.groups="drop") %>%
    mutate(Trend=add_stl_trend_m(Cases+1)$trend-1 %>%  pmax(0)) |>
    pivot_longer(c("Cases","Trend"),names_to = "measure",values_to = "value")
  
  bind_rows(wd,cs) %>%
    mutate(region=label)
}

plot_data <- bind_rows(
  joint_data_for("Vancouver","Iona Island"),
  joint_data_for("Richmond","Lulu Island"),
  #joint_data_for(c("Fraser North","Fraser South"),c("Annacis Island"=0.8,"Northwest Langley"=0.2)),
  joint_data_for(c("Fraser North","Fraser South"),"Annacis Island",label="Annacis / Fraser North/South"),
  joint_data_for("North Shore/Coast Garibaldi","Lions Gate"),
)

stations <- c("Iona Island / Vancouver"=51442,
              "Lions Gate / North Shore/Coast Garibaldi"=833,
              "Lulu Island / Richmond"=837,
              "Annacis / Fraser North/South"=43723)
weather_data<-weathercan::weather_dl(stations,interval = "day",start=min(wastewater_data$Date)-3) %>%
  mutate(Date=date) %>%
  mutate(region=setNames(names(stations),as.integer(stations))[as.character(station_id)]) %>%
  select(Date,total_rain,region) %>%
  mutate(total_rain=coalesce(total_rain,0)) %>%
  group_by(region) %>%
  arrange(Date)%>%
  mutate(rain=roll::roll_mean(total_rain,3)) %>%
  #mutate(rain=zoo::rollmean(total_rain,3,na.pad = TRUE,align = "right")) %>%
  #mutate(rain=(total_rain+lag(total_rain,1,order_by = Date)+lag(total_rain,2,order_by = Date))/3)%>%
  mutate(s=rain/mean(rain,na.rm=TRUE),
         value=rain) 
  
beginning_date <- as.Date("2020-10-01")
change_methods_date <- as.Date("2021-01-01")
change_methods_end_date <- as.Date("2021-12-15")



wastewater_colours<- setNames(c(MetBrewer::met.brewer("Egypt",4),"darkgrey"),
                              c("Cases","Concentration","Flow adjusted","PHAC","Rainfall"))

pd <- plot_data %>%
  filter(measure!="Cases") |>
  mutate(measure=recode(measure,"Trend"="Cases")) |>
  bind_rows(weather_data %>% mutate(measure="Rainfall")) %>%
  mutate(measure=factor(measure,levels=c("Cases","Concentration","Flow adjusted","PHAC","Rainfall") %>% rev)) %>%
  group_by(measure,region) %>%
  filter(Date>=beginning_date) %>%
  left_join((.) %>% filter(Date>=change_methods_date,Date<=change_methods_end_date) %>%
              group_by(measure,region) %>%
              summarise(mean_value=mean(value,na.rm=TRUE)),by=c("measure","region")) %>%
  mutate(s=value/mean_value)

pd %>% 
  #filter(name!="Rainfall") %>%
  #filter(!is.na(s)) %>%
  ggplot(aes(x=Date,y=s,colour=measure)) +
  geom_vline(xintercept = change_methods_date,linetype="dotted") +
  geom_rect(data=as_tibble(1),xmin=-Inf,xmax=change_methods_date,ymin=-Inf,ymax=Inf,
            fill="grey",colour=NA,inherit.aes = FALSE,alpha=0.5) +
  geom_rect(data=as_tibble(1),xmin=change_methods_end_date,xmax=Inf,ymin=-Inf,ymax=Inf,
            fill="grey",colour=NA,inherit.aes = FALSE,alpha=0.5) +
  geom_line() +
  #geom_point(shape=21,data=~filter(.,name=="Wastewater")) +
  facet_wrap(~region) +
  theme_bw() +
  scale_colour_manual(values=wastewater_colours[(unique(as.character(pd$measure)))]) +
  scale_y_continuous() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(title="Wastewater COVID concentration vs case counts",
       x=NULL,y=NULL,colour=NULL)
```

```{r wastewater-covid-zoomed}
pd %>% filter(Date>=as.Date("2021-12-01")) %>%
  #filter(!is.na(s)) %>%
  ggplot(aes(x=Date,y=s,colour=measure)) +
  geom_vline(xintercept = change_methods_date,linetype="dotted") +
  geom_line() +
  geom_point(shape=21,data=~filter(.,measure %in% c("Concentration","Flow adjusted","PHAC"))) +
  facet_wrap(~region) +
  theme_bw() +
  scale_colour_manual(values=wastewater_colours[(unique(as.character(pd$measure)))]) +
  scale_y_continuous() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(title="Recent wastewater COVID concentration vs case counts",
       x=NULL,y=NULL,colour=NULL)
```

```{r wastewater-covid-zoomed-log}
pd %>% filter(Date>=as.Date("2021-12-01")) %>%
  filter(measure!="Rainfall") |>
  #filter(!is.na(s)) %>%
  ggplot(aes(x=Date,y=s,colour=measure)) +
  geom_vline(xintercept = change_methods_date,linetype="dotted") +
  geom_line() +
  geom_point(shape=21,data=~filter(.,measure %in% c("Concentration","Flow adjusted","PHAC"))) +
  facet_wrap(~region) +
  theme_bw() +
  scale_colour_manual(values=wastewater_colours[(unique(as.character(pd$measure)))]) +
  scale_y_continuous(trans="log") +
  theme(legend.position = "bottom",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(title="Recent wastewater COVID concentration vs case counts",
       x=NULL,y="(log scale)",colour=NULL)
```

```{r wastewater-covid-2, eval=FALSE, include=FALSE}
plot_data %>%
  group_by(region)%>%
  arrange(Date) %>%
  mutate(Cases=Trend) %>%
  #mutate(Cases=zoo::rollmean(Cases,7,na.pad = TRUE,align = "center")) %>%
  pivot_longer(c("Cases","Concentration","Flow adjusted")) %>%
  group_by(name,region) %>%
  bind_rows(weather_data %>% mutate(name="Rainfall")) %>%
  mutate(name=factor(name,levels=c("Cases","Concentration","Flow adjusted","Rainfall"))) %>%
  filter(Date>=change_methods_date) %>%
  mutate(s=value/mean(value,na.rm=TRUE)) %>%
  ggplot(aes(x=Date,y=s,colour=name)) +
  geom_line() +
  facet_wrap(~region) +
  theme_bw() +
  scale_colour_manual(values=wastewater_colours) +
  scale_y_continuous() +
  theme(legend.position = "bottom",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) +
  labs(title="Wastewater COVID concentration vs case counts",
       x=NULL,y=NULL,colour=NULL) +
  coord_cartesian(ylim = c(0,7))
```


## Cases in young children
```{r under-10}
data <- get_british_columbia_case_data() %>%
  count(Date=`Reported Date`,HA=`Health Authority`,Age=`Age group`,name="Cases") %>%
  complete(Date,HA,Age,fill=list(Cases=0))

ha_pop_age <- read_csv(here::here("data/ha_pop_age.csv")) %>%
  pivot_longer(matches("\\d+"),names_to="Age",values_to="Count") %>%
  mutate(Age=ifelse(Age=="LT1",0,Age)) %>%
  mutate(top=strsplit(Age,"-") %>% lapply(last) %>% unlist %>% as.integer()) %>%
  mutate(t=floor(top/10)*10+9) %>%
  mutate(`Age group`=paste0(t-9,"-",t)) %>%
  mutate(`Age group`=recode(`Age group`,"0-9"="<10","NA-NA"="90+")) %>%
  group_by(HA=`Health Authority`,Age=`Age group`) %>%
  summarize(Total=first(Total),Count=sum(Count),.groups="drop") %>%
  mutate(Share=Count/Total)

dd<-data %>%
  filter(HA!="Out of Canada",Age!="Unknown") %>%
  filter(Date>=as.Date("2020-07-01")) %>%
  left_join(ha_pop_age,by=c("HA","Age")) %>%
  mutate(AG=case_when(Age=="<10" ~ "Under 10", TRUE ~ "10 and over")) %>%
  mutate(AG=factor(AG,levels=c("Under 10","10 and over"))) %>%
  group_by(Date,HA,AG) %>%
  summarise(Population=sum(Count),Cases=sum(Cases),Total=first(Total),.groups="drop") %>%
  bind_rows((.) %>% 
              group_by(Date,AG) %>% 
              summarize(Population=sum(Population),
                        Total=sum(Total),
                        Cases=sum(Cases)) %>%
              mutate(HA="British Columbia")) %>%
  group_by(HA,AG) %>%
  arrange(Date) %>%
  mutate(Trend=pmax(0,add_stl_trend_m(Cases+5)$trend-5)) %>%
  mutate(across(c(Trend,Cases),function(d)d/.data$Population*100000))

# stl_fan <- dd %>%
#   group_by(HA,AG) %>%
#   get_stl_fan()
  

dd %>%
  filter(Date>=as.Date("2020-08-01")) %>%
  #left_join(stl_fan %>% group_by(HA,AG) %>% summarize(max_date=min(Date),.groups="drop"), by=c("HA","AG")) %>%
  #filter(Date<=max_date) %>%
  ggplot(aes(x=Date,y=Trend,colour=AG)) +
  geom_point(shape=21,aes(y=Cases),alpha=0.5,size=0.5) +
  # geom_ribbon(data=stl_tail,aes(x=Date,ymin=min,ymax=max,fill=AG,color=AG,group=AG),
  #             inherit.aes=FALSE,show.legend = FALSE,alpha=0.5) +
  geom_line() +
  #geom_line(data=stl_fan,aes(x=Date,y=value,colour=AG,group=interaction(run,AG)),size=0.25) +
  theme_bw() +
  scale_x_date(breaks="month",date_labels = "%b") +
  scale_y_continuous() +
  scale_color_manual(values=sanzo::duos$c070) +
  scale_fill_manual(values=sanzo::duos$c070,guide='none') +
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle=40,hjust=1)) +
  #scale_y_continuous(labels=scales::comma) +
  labs(title=paste0("BC COVID-19 cases",
                    " (up to ",strftime(max(data$Date),format="%b %d, %Y"),")"),
       x=NULL,y="Daily COVID-19 incidence per 100k population",
       colour=NULL,
       caption="MountainMath, Data: BCCDC") +
  facet_wrap(~HA,scales="free_y") 
```
