---
title: "statcan_wastewater"
author: "Jens von Bergmann"
date: "28/02/2022"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(tidyverse)
source(here::here("R/helpers.R"))
```

```{r}
tmp <- tempfile()
download.file("https://www150.statcan.gc.ca/n1/pub/38-26-0002/2022001/Wastewater_COVID19_2022_02_18.zip",tmp)

file.exists(tmp)
ls <- unzip(tmp,exdir = tempdir())

overview <- read_csv(ls[13])
sites <- read_csv(ls[grepl("Site\\.",ls)]) %>%
  filter(grepl("Vancouver",name)) %>%
  mutate(Plant=gsub(" +Vancouver$","",name)) %>%
  select(siteID,Plant)
lookup <- read_csv(ls[grepl("Lookup\\.",ls)])

sample <- read_csv(ls[grepl("Sample\\.",ls)])

ww_data <- read_csv(ls[grepl("WWMeasure",ls)]) %>%
  mutate(siteID=substr(sampleID,1,3)) %>%
  inner_join(sites,by="siteID") %>%
  left_join(sample %>% select(sampleID,dateTimeStart,dateTimeEnd) %>%
              mutate(Date=as.Date(dateTimeEnd)),by="sampleID")

# vli_data <- CanCovidData::get_british_columbia_hr_case_data() %>%
#   filter(`Health Region`=="Vancouver") %>%
#   filter(Date>=as.Date("2020-03-01")) %>%
#   arrange(Date) %>%
#   mutate(stl=add_stl_trend_m(Cases+5)) %>%
#   mutate(Trend=pmax(0,stl$trend-5))

bc_cases <- CanCovidData::get_british_columbia_hr_case_data() %>%
  select(Date, HA=`Health Authority`,HR=`Health Region`,Cases) %>%
  mutate(Plant=case_when(HR=="Vancouver" ~ "Iona Island",
                         HR=="Richmond" ~ "Lulu Island",
                         HR=="North Shore/Coast Garibaldi" ~ "Lions Gate",
                         HR %in% c("Fraser North","Fraser South") ~ "Annacis Island",
                         TRUE ~ "Other")) %>%
  filter(Plant!="Other") %>%
  group_by(Date,Plant) %>%
  summarise(Cases=sum(Cases),.groups="drop") %>%
  filter(Date>=as.Date("2020-07-01")) %>%
  group_by(Plant) %>%
  arrange(Date) %>%
  mutate(stl=add_stl_trend_m(Cases+5)) %>%
  mutate(Trend=pmax(0,stl$trend-5))

stations <- c("Iona Island"=51442,
              "Lions Gate"=833,
              "Lulu Island"=837,
              "Annacis Island"=43723)
weather_data<-weathercan::weather_dl(stations,interval = "day",start=min(ww_data$Date)-5) %>%
  mutate(Date=date) %>%
  mutate(Plant=setNames(names(stations),as.integer(stations))[as.character(station_id)]) %>%
  select(Date,total_rain,Plant,mean_temp) %>%
  left_join(filter(.,Plant=="Iona Island") %>% select(Date,mean_temp_fallback=mean_temp),by="Date") %>%
  mutate(mean_temp=coalesce(mean_temp,mean_temp_fallback)) %>%
  select(-mean_temp_fallback) %>%
  mutate(total_rain=coalesce(total_rain,0)) %>%
  group_by(Plant) %>%
  arrange(Date)%>%
  mutate(rain=roll::roll_mean(total_rain,3)) %>%
  #mutate(rain=zoo::rollmean(total_rain,3,na.pad = TRUE,align = "right")) %>%
  #mutate(rain=(total_rain+lag(total_rain,1,order_by = Date)+lag(total_rain,2,order_by = Date))/3)%>%
  mutate(s=rain/mean(rain,na.rm=TRUE),
         value=rain)

plants <- c("Annacis Island","Iona Island","Lions Gate","Lulu Island","Northwest Langley")
used_plants <- c("Annacis Island","Iona Island","Lions Gate","Lulu Island")

wastewater_data <- plants %>% 
  lapply(get_data_for_plant) %>%
  bind_rows() %>%
  complete(Date=as.Date(c("2021-12-25","2020-12-25")),Plant,Version) 


wd<-ww_data %>%
  mutate(t=case_when(grepl("cov",type) ~ "cov",
                     TRUE ~ type)) %>%
  group_by(reportDate,t) %>%
  summarise(value=mean(value))
```


```{r}
all_data <- ww_data %>% 
  group_by(Plant,Date,type) %>%
  summarise(value=mean(value),.groups="drop") %>%
  pivot_wider(names_from = type,values_from = value) %>% 
  left_join(bc_cases %>% select(Date,Plant,Trend), by=c("Date","Plant")) %>%
  left_join(weather_data %>% select(Date,Plant,rain=total_rain,mrain=rain,mean_temp),by=c("Date","Plant")) %>%
  mutate(d=difftime(Date,min(Date),units="days") %>% as.integer) %>%
  mutate(wastewater=covN1+covN2) %>%
  mutate(cov=(covN1+covN2)/2) %>%
  mutate_at(c("Trend","covN1","covN2","nPPMoV","cov"),log) %>%
  mutate_at(c("rain","mrain"),function(d)log(d+1)) %>%
  group_by(Plant) %>%
  mutate(lagc=lag(cov,order_by = Date),
         leadc=lead(cov,order_by = Date),
         leadc2=lead(cov,n=2,order_by = Date),
         leadc3=lead(cov,n=3,order_by = Date),
         CnPPMoV=(cov)/nPPMoV,
         lagCnPPMoV=lag(CnPPMoV,order_by = Date),
         leadCnPPMoV=lead(CnPPMoV,order_by = Date),
         leadCnPPMoV2=lead(CnPPMoV,n=2,order_by = Date),
         leadCnPPMoV3=lead(CnPPMoV,n=3,order_by = Date),
         leadCnPPMoV4=lead(CnPPMoV,n=4,order_by = Date),
         lagRain=lag(rain,n=3,order_by = Date)
  ) %>%
  ungroup()


predictions_for <- function(plant){
  l_data <- all_data %>% filter(Plant==plant)
  model_data  <- l_data %>% 
    filter(Date<=as.Date("2021-12-20"))
  
  formula <- Trend~covN1+covN2+nPPMoV+lagc+leadc+leadc2+leadc3+mean_temp+mrain
  
  m.rf <- randomForest::randomForest(formula,#+
                                   #CnPPMoV+lagCnPPMoV+leadCnPPMoV+leadCnPPMoV2+leadCnPPMoV3+leadCnPPMoV4,
                                   data=model_data,
                                   mtry = 3,
                                   importance = TRUE, 
                                   na.action = na.omit)
  
  #randomForest::varImpPlot(m.rf)
  #m.glm_plain <- glm(formula, data=model_data)
  m.glm <- glm(formula,#+
               #CnPPMoV+lagCnPPMoV+leadCnPPMoV+leadCnPPMoV2+leadCnPPMoV3+leadCnPPMoV4
               data=model_data)
  
  
  # m.glm.rf <- randomForest::randomForest(res.glm~nPPMoV+lagc+leadc+leadc2+leadc3+mean_temp+mrain,
  #                                        #CnPPMoV+lagCnPPMoV+leadCnPPMoV+leadCnPPMoV2+leadCnPPMoV3+leadCnPPMoV4,
  #                                        data=model_data %>% mutate(res.glm=c(m.glm_plain$residuals)),
  #                                        mtry = 3,
  #                                        importance = TRUE, 
  #                                        na.action = na.omit)
  
  m.arima<-forecast::Arima(ts(model_data$Trend),xreg = model_data %>% 
                             select(covN1, covN2, nPPMoV,mrain,mean_temp) %>% as.matrix,
                           lambda="auto")
  
  
  
  m.svm <- e1071::svm(formula,
                      kernel="linear",
                      data=model_data)
  
  wastewater_fac <- mean(exp(model_data$Trend))/mean(model_data$wastewater)
  
  pd <- l_data %>% 
    mutate(n=row_number() %>% as.character) %>%
    mutate(rf=predict(m.rf,newdata = .) %>% exp) %>%
    mutate(glm=predict(m.glm,newdata = .) %>% exp) %>%
    #mutate(glm.rf=predict(m.glm_plain,newdata = .)+predict(m.glm.rf,newdata = .) %>% exp) %>%
    left_join(predict(m.svm,newdata=l_data) %>% 
                as.data.frame() %>% 
                setNames("svm") %>%
                mutate(n=rownames(.),
                       svm=exp(svm)) %>%
                as_tibble(),by="n") %>%
    #mutate(svm=c(NA,NA,NA,NA,predict(m.svm,newdata = .),NA,NA,NA) %>% exp) %>%
    mutate(arima=predict(m.arima,newxreg = l_data %>% 
                           select(covN1, covN2, nPPMoV,mrain,mean_temp) %>% 
                           as.matrix)$pred %>%
             forecast::InvBoxCox(lambda=m.arima$lambda)  %>% exp) %>%
    #mutate(wastewater_scaled=wastewater*wastewater_fac)
    mutate(wastewater_scaled=zoo::rollmean(wastewater,k=5,na.pad=TRUE)*wastewater_fac)
  
  pd %>%
    mutate(Cases=exp(Trend)) %>%
    #filter(name!="arima") %>%
    mutate(Plant=plant)
}

model_colours <- c(Cases="black",svm="brown",wastewater_scaled="steelblue",glm="purple")

used_plants %>%
  lapply(predictions_for) %>%
  bind_rows() %>%
  #pivot_longer(c("Cases","rf","glm","arima","svm","wastewater_scaled")) %>%
  pivot_longer(c("Cases","svm","wastewater_scaled","glm")) %>%
  ggplot(aes(x=Date,y=value,colour=name)) +
  geom_line() +
  scale_colour_manual(values=model_colours) +
  facet_wrap(~Plant,scales="free_y") +
  #coord_cartesian(y=c(0,400)) +
  scale_y_continuous(trans="log",breaks=5*2^seq(0,10)) +
  theme(legend.position = "bottom") +
  geom_vline(xintercept = as.Date("2021-12-15")) +
  #geom_line(aes(y=Trend),data=bc_cases %>% filter(Date>=as.Date("2021-12-15")),colour="steelblue") +
  scale_x_date(breaks = "month",date_labels = "%b")

```
