on:
  schedule:
    - cron: "55 0,23 * * *"
    
name: Render BC Trends hourly

jobs:
  render:
    name: Render BC Trends hourly
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      nextzen_API_key: ${{ secrets.NEXTZEN_API_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - uses: actions/checkout@v2 
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: "[Custom block] [macOS] Install spatial libraries"
        if: runner.os == 'macOS'
        run: |
          # conflicts with gfortran from r-lib/actions when linking gcc
          #rm '/usr/local/bin/gfortran'
          brew install udunits
          brew install pkg-config gdal proj geos udunits
      - name: Install rmarkdown, remotes, and required packages
        run: |
          install.packages("remotes")
          install.packages("ggplot2")
          install.packages("tidyr")
          install.packages("dplyr")
          install.packages("roll")
          install.packages("readr")
          install.packages("MetBrewer")
          install.packages("ggrepel")
          install.packages("ggtext")
          install.packages("rmarkdown")
          install.packages("here")
          install.packages("sanzo")
          install.packages("scales")
          install.packages("cansim")
          install.packages("stringr")
          install.packages("rvest")
          install.packages("segmented")
          install.packages("sf",type="binary")
          install.packages("patchwork")
          remotes::install_github("mountainMath/cansim")
          remotes::install_github("mountainMath/CanCovidData")
        shell: Rscript {0}
      - name: Render BC Trends
        run: |
          Rscript -e 'rmarkdown::render("bc_covid_trends.Rmd")'
      - name: Render Two COVID Canadas
        run: |
          Rscript -e 'rmarkdown::render("two_covid_canadas.Rmd")'
      - name: Render Vaccination Tracker
        run: |
          Rscript -e 'rmarkdown::render("vaccination_tracker.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -m 'Re-build bc_covid_trends.Rmd' || echo "No changes to commit"
          git commit bc_covid_trends.md  bc_covid_trends_files -m 'Re-build bc_covid_trends.Rmd' || echo "No changes to commit"
          git commit two_covid_canadas.md two_covid_canadas_files -m 'Re-build two_covid_canadas.Rmd' || echo "No changes to commit"
          git commit open_table.md open_table_files -m 'Re-build open_table.Rmd' || echo "No changes to commit"
          git commit vaccination_tracker.md vaccination_tracker_files -m 'Re-build vaccination_tracker.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
